# Generated by Django 5.1.7 on 2025-03-21 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="attachment",
            field=models.FileField(
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"])
                ],
            ),
        ),
    ]
