# Generated by Django 5.1.7 on 2025-03-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0002_alter_summary_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="summary",
            name="summary_length",
            field=models.CharField(
                choices=[
                    ("SHORT", "Short"),
                    ("MEDIUM", "Medium"),
                    ("LONG", "Long"),
                ],
                default="SHORT",
            ),
        ),
    ]
